_RULES_MK_VARS_NAME := sms
_RULES_MK_VARS_DESCRIPTION := Send SMS through RDCom API
_RULES_MK_VARS_COPYRIGHT := 2025 © Andrea Funtò
_RULES_MK_VARS_LICENSE := MIT
_RULES_MK_VARS_LICENSE_URL := https://opensource.org/license/mit/
_RULES_MK_VARS_VERSION_MAJOR := 0
_RULES_MK_VARS_VERSION_MINOR := 0
_RULES_MK_VARS_VERSION_PATCH := 1
_RULES_MK_VARS_VERSION=$(_RULES_MK_VARS_VERSION_MAJOR).$(_RULES_MK_VARS_VERSION_MINOR).$(_RULES_MK_VARS_VERSION_PATCH)
_RULES_MK_VARS_MAINTAINER=dihedron.dev@gmail.com
VENDOR=dihedron.dev@gmail.com
PRODUCER_URL=https://github.com/dihedron/
DOWNLOAD_URL=$(PRODUCER_URL)snoop
_RULES_MK_VARS_METADATA_PACKAGE=$$(grep "module .*" go.mod | sed 's/module //gi')/version
#_RULES_MK_VARS_DOTENV_VAR_NAME=

_RULES_MK_FLAG_MINIMUM_VERSION=202502220945
_RULES_MK_ENABLE_CGO=0
_RULES_MK_ENABLE_GOGEN=1
_RULES_MK_ENABLE_RACE=0
#_RULES_MK_STATIC_LINK=1
#_RULES_MK_ENABLE_NETGO=1
#_RULES_MK_STRIP_SYMBOLS=1
#_RULES_MK_STRIP_DBG_INFO=1
#_RULES_MK_FORCE_DEP_REBUILD=1

include rules.mk

.PHONY: clean-cache ## remove all cached build entries
clean-cache:
	@go clean -x -cache
